---
title: "STA-230 - Introduction to Data Science (Fall 2023)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

Last updated: `r format(Sys.time(), "%a %b %e %Y, %H:%M")`

### Syllabus

Welcome to the course website for STA 230, Introduction to Data Science. To begin, you can find the course syllabus linked below:

- [Click here](syllabus230f23.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper left.  

Please note: material will not be posted until we've reached that point in the course.

### Labs

STA 230 uses a *workshop style* class format. This means that the majority of our class time will be devoted towards collaboratively working through guided lab activities. You should consult the syllabus for a more detailed description of lab procedures and expectations.

**Lab Topics and Links**:

- Introduction to `R`
    - [Lab 1 (intro)](labs/intro1.html)
    - [Lab 2 (R Markdown)](labs/intro2.html)
    - Optional Lab (common hypothesis tests)
    - Labs due as a single document on pweb 9/6
- Data visualization
    - [Lab 3 (intro to `ggplot`)](labs/ggplot_lab3.html)
    - [Lab 4 (Themes and Scales - `ggplot`)](labs/lab4.html)
    - [Bonus Lab (`ggplot`)](labs/ggplot2_bonus_miller.html)
    - Labs due (excluding bonus) as a single document 9/13 at 11:59pm
- Data manipulation
    - [Lab 5 (reshaping data with `tidyr`)](labs/tidyr.html)
      + [Visual aid (pivot)](scratch/pivot_summary.pdf)
      + [Visual aid (aes)](scratch/aes_visual_aid.pdf)
    - [Lab 6 (manipulation with `dplyr`)](labs/dplyr.html)
      + [Summary summary](scratch/summarize_vs_mutate.html)
    - [Lab 7 (merging and joining)](labs/joins.html)
    - Labs due (excluding bonus) as a single document 9/25 at 11:59pm
    - Optional lab (functions, iteration, and files)
- Misc topics
    - [Lab 8 (string processing with `stringr`)](labs/stringr.html)
    - [Lab 9 (functions conditionals and files)](labs/functions.html)
    - [Lab 10 (dates)](labs/dates.html)
    - Labs due as a single document (MUST BE HTML) by 10/9 at 11:59pm
- Interactive data visualizations
    - [Lab 11 (interactive graphics with `plotly`)](labs/plotly.html)
    - [Lab 12 (maps with `ggplot`)](labs/maps.html)
    - Labs due Wednesday AFTER break, 10/25 at 11:59pm
- R Shiny applications
    - [Lab 13 Shiny UI](labs/shiny_ui.html)
    - [Lab 14 Shiny Server](labs/shiny_server.html)
    - [Lab 15 Shiny Style `r emo::ji("sunglasses")`](labs/shiny_style.html)
    - [Resources for Shiny](labs/shiny_reference_page.html)
    - Labs due 11/3 at 11:59pm
- Regression
    - [Lab 16 Simple Linear Regression](labs/simple_linear.html)
    - [Lab 17 Multivariate Regression](labs/multivariate_regression.html)
    - [Lab 18 Logistic Regression](labs/logistic.html)
    - Labs due 11/29 at 11:59pm
- Principal component analysis
    - Lab XX (intro to PCA)
- Clustering
    - Lab XX (partitional clustering), Lab XX (hierarchical clustering)

    
### Misc Announcements

10/11 Please fill out this [mid semester course evaluation!](https://grinnell.co1.qualtrics.com/jfe/form/SV_ezJFu81fxhFdKIK)

Math and Stats concentration welcome session, 2nd year students only, Thursday Oct 5 11AM - 12PM in Math Commons area (Noyce 2520). Faculty and SEPC members will be present. Ice cream and popsicles.

[MASS Talk](scratch/mass.png)  Graduate school in statistics, seminar, Thursday November 9 at 4pm in Noyce 2517
    
### Course Summary and Cheatsheets

[`ggplot2` Cheatsheet](https://www.maths.usyd.edu.au/u/UG/SM/STAT3022/r/current/Misc/data-visualization-2.1.pdf)

[`stringr` Cheatsheet](https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_strings.pdf)

[`lubridate` Cheatsheet](https://evoldyn.gitlab.io/evomics-2018/ref-sheets/R_lubridate.pdf)

[R Shiny Cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/shiny.pdf)

[R Markdown Cheatsheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/rmarkdown.pdf)

[Summary](courseSummary.html)


<!-- - Introduction to `R` -->
<!--     - [Lab 1 (intro)](s230s23/intro1.html), [Lab 2 (R Markdown)](s230s23/intro2.html), [Optional Lab (common hypothesis tests)](s230s23/ht.html) -->
<!-- - Data visualization -->
<!--     - [Lab 3 (intro to `ggplot`)](s230s23/ggplot.html), [Lab 4 (effective data visualizations)](s230s23/ggplot2.html) -->
<!-- - Data manipulation -->
<!--     - [Lab 5 (reshaping data with `tidyr`)](s230s23/tidyr.html), [Lab 6 (manipulation with `dplyr`)](s230s23/dplyr.html), [Lab 7 (merging and joining)](s230s23/joins.html) -->
<!--     - [Optional lab (functions, iteration, and files)](s230s23/misc.html) -->
<!-- - Working with strings -->
<!--     - [Lab 8 (string processing with `stringr`)](s230s23/strings.html) -->
<!-- - Interactive data visualizations -->
<!--     - [Lab 9 (interactive graphics with `plotly`)](s230s23/plotly.html), [Lab 10 (maps with `ggplot` and `leaflet`)](s230s23/maps.html) -->
<!-- - R Shiny applications -->
<!--     - [Lab 11 (intro to `shiny`)](s230s23/shiny.html) -->
<!-- - Principal component analysis -->
<!--     - [Lab 12 (intro to PCA)](s230s23/pca.html) -->
<!-- - Clustering -->
<!--     - [Lab 13 (partitional clustering)](s230s23/clustering1.html), [Lab 14 (hierarchical clustering)](s230s23/clustering2.html) -->
<!-- - Modeling a numeric outcome -->
<!--     - [Lab 15 (modeling a numeric outcome)](s230s23/model1.html), [Lab 16 (cross-validation)](s230s23/model2.html) -->
<!-- - Modeling a categorical outcome -->
<!--     - [Lab 17 (modeling a categorical outcome)](s230s23/model3.html), [Lab 18 (decision tree models)](s230s23/trees.html) -->


### Homework Assignments

Throughout the semester there will be 6-7 homework assignments:

- [Homework #1](hw/hw1.html)
  - [Template .Rmd File](hw/hw1.Rmd)
  - Due date: 9/6
- [Homework #2](hw/hw2.html)
  - Due date: 9/15 at 11:59pm
- [Homework #3](hw/hw3.html)
  - Due date: Monday 9/25 at 11:59pm
- [Homework #4](hw/hw4.html)
  - Due date: Friday 10/25 at 11:59pm

### Projects


1. Data cleaning and visualization take-home (midterm 1)
    - Current plan is to release this Tuesday (9/26) at 8am and have it due Thursday (9/28) by 11:59pm
    - No class on Wednesday (9/27) to allow extra time
    - Will offer extra office hours during those times
    - [Practice take-home (from Spring 2023)](https://remiller1450.github.io/s230f23/takehome2.pdf)
2. R Shiny Presentations (midterm 2)
    - Details [here!](projects/rshiny_project.html)
    - Proposal due 10/27
    - Data cleaning/visualization sketch due 11/1
    - Final code, data, and report due 11/10
    - Don't forget about the [resources page](labs/shiny_reference_page.html)
    - [ZOOM LINK](https://uiowa.zoom.us/j/93206777932?pwd=TVhZNnUzWVI3eWppbmFhVnBZMHZzZz09)
    - [WEBEX LINK](https://grinnellcollege.webex.com/grinnellcollege-en/j.php?MTID=m2aacef174631ea0fc8f532fabca5a670)
    - [webex link 2 (try this first)](https://grinnellcollege.webex.com/meet/noltecollin)
    - [Submission Format Example](data/submission.zip)
        + Zip file with raw data, clean data, cleaning script and app

<!-- There will be 3 major projects during the semester. Details on each project will be posted no later than 2 weeks before the project's first deadline. -->

<!-- 1. Data cleaning and visualization take-home -->
<!--     - [Description (available now)](s230s23/takehome1.html) -->
<!--     - Instructions and Data (emailed Wednesday 2/15 at noon) -->
<!--     - Due Sunday 2/19 at 11:59pm -->
<!-- 2. R Shiny application -->
<!--     - [Project Description](s230s23/project2.html) -->
<!--     - All app code is due Friday 3/17 at 11:59pm -->
<!-- 3. Data analysis (final) -->
<!--     - [Project Description](s230s23/final.html) -->
<!--     - Update email is due Monday 5/1 at 11:59pm, your email should include a 1-paragraph written description of your progress accompanied by a code file or screenshots. -->


### Recommended Readings

The following readings are *recommended* in conjunction with the block of material they cover. They are intended to provide another perspective on the topics we'll cover:

- Introduction to R
    - [Ch 4 (R basics) - R for Data Science](https://r4ds.had.co.nz/workflow-basics.html)
    - [Ch 27 (R Markdown - R for Data Science)](https://r4ds.had.co.nz/r-markdown.html)
- Data Visualization
    - [Ch 3 (Data visualization) - R for Data Science](https://r4ds.had.co.nz/data-visualisation.html)
    - [Ch 2.1, 2.2, 2.3, 2.4 (Data visualization case study) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizI.html)
    - [Ch 3 (ggplot) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-vizII.html)
- Data Manipulation
    - [Ch 12 (Tidy data) - R for Data Science](https://r4ds.had.co.nz/tidy-data.html)
    - [Ch 4 (Data wrangling) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-dataI.html)
    - [Ch 5 (Joins) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-join.html)
    - [Ch 13 (Relational data) - R for Data Science](https://r4ds.had.co.nz/relational-data.html)
- Working with strings
    - [Ch 14 (Strings) - R for Data Science](https://r4ds.had.co.nz/strings.html)
<!-- - Interactive Data Visualizations -->
<!--     - [Ch 2.1 (Intro Plotly) - Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/overview.html#intro-plotly) -->
<!--     - [Ch 17 (Maps and Geospatial data) - Modern Data Science with R](https://mdsr-book.github.io/mdsr2e/ch-spatial.html#motivation-whats-so-great-about-geospatial-data) -->
<!-- - Principal Component Analysis -->
<!--     - [Ch 12.1 and 12.2 (PCA) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf) -->
<!-- - Clustering  -->
<!--     - [Ch 12.4 (Clustering) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf) -->
<!-- - Modeling a numeric outcome -->
<!--     - [Ch 2.1 and 2.2 (Concepts in statistical learning) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf) -->
<!--     - [Ch 3.1, 3.2, and 3.3 (Linear regression) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf) -->
<!-- - Cross-validation -->
<!--     - [Stanford's Intro to Statistical Learning video 5.2 (k-fold CV)](https://www.youtube.com/watch?v=AMfvd_hLssE&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=28) -->
<!--     - [Stanford's Intro to Statistical Learning video 5.3 (CV the right and wrong way)](hhttps://www.youtube.com/watch?v=jgoa28FR__Y&list=PLoROMvodv4rOzrYsAxzQyHb8n_RWNuS1e&index=29) -->
<!-- - Modeling a categorical outcome -->
<!--     - [Ch 4.1, 4.2, and 4.3 (Classification and logistic regression) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf) -->
<!-- - Tree-based models -->
<!--      - [Ch 8.1 and 8.2 (Decision trees and random forests) - Intro to Statistical Learning](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf) -->
