# --- Generate Synthetic Cattle Dataset (Improved Associations) ---
# --- Generated by ChatGPT 10/29/25 ---
set.seed(123)
N <- 300

# --- Categorical variables ---
sex <- sample(c("Male", "Female"), N, replace = TRUE, prob = c(0.45, 0.55))
breed <- sample(c("Angus", "Hereford", "Charolais", "Brahman"), N, replace = TRUE)
feed_type <- sample(c("Pasture", "Grain", "Mixed"), N, replace = TRUE, prob = c(0.4, 0.4, 0.2))
vaccine <- sample(c("Yes", "No"), N, replace = TRUE, prob = c(0.7, 0.3))
hormone_treatment <- sample(c("Yes", "No"), N, replace = TRUE, prob = c(0.3, 0.7))

# --- Continuous variables ---
age_months <- round(runif(N, 6, 60), 1)

# Breed-level baseline effects
breed_effect_weight <- c(Angus = 0, Hereford = 15, Charolais = 25, Brahman = 10)
breed_effect_horn   <- c(Angus = 0, Hereford = 3, Charolais = 6, Brahman = 9)
breed_effect_milk   <- c(Angus = 7, Hereford = 8, Charolais = 6, Brahman = 5)

# Feed effects
feed_effect_weight <- c(Pasture = -10, Grain = 20, Mixed = 10)
feed_effect_milk   <- c(Pasture = -2, Grain = 2, Mixed = 1)

# Sex effects
sex_effect_weight <- ifelse(sex == "Male", 30, 0)

# --- Weight ---
weight <- round(
  200 +
    5 * age_months +
    breed_effect_weight[breed] +
    feed_effect_weight[feed_type] +
    sex_effect_weight +
    rnorm(N, 0, 25),
  1
)

# --- Horn length (males only), depends on breed and weight ---
horn_length <- ifelse(
  sex == "Male",
  pmax(0, rnorm(
    N,
    mean = 2 + 0.25 * (weight / 100) + breed_effect_horn[breed] + rnorm(N, 0, 1)
  )),
  0
)

# --- Health score ---
health_score <- round(
  80 +
    0.1 * age_months -
    0.5 * (vaccine == "No") -
    0.3 * (hormone_treatment == "Yes") +
    0.05 * (weight / 10) +
    rnorm(N, 0, 5),
  1
)

# --- Milk yield (females only), depends on feed, breed, and age --- and health
milk_yield <- ifelse(
  sex == "Female",
  pmax(
    0,
    rnorm(
      N,
      mean = breed_effect_milk[breed] +
        feed_effect_milk[feed_type] +
        0.04 * age_months + 
        rnorm(N, 0, 1.5)
    )
  ),
  0
)


# --- Combine all ---
cattle <- data.frame(
  id = 1:N,
  sex,
  breed,
  age_months,
  horn_length,
  weight,
  feed_type,
  vaccine,
  hormone_treatment,
  milk_yield,
  health_score
)

# Preview
head(cattle)

fwrite(cattle, file = "~/gitsite/data/cattle.csv")
